# Pygor is part of the IGoR (Inference and Generation of Repertoires) software.
# Pygor Python package can be used to post process files generated by IGoR.
# Copyright (C) 2018 Quentin Marcou & Wout van Helvoirt

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


"""Test file for testing pygor.util.io file."""


import pandas
import pytest

from pygor.util.io import read_fasta_as_dataframe


@pytest.mark.parametrize('infile, expected', [
    ('tests/test_data/IGH_mus_musculus/ref_genomes/genomicJs.fasta',
     pandas.DataFrame(
         [['V00762|IGHJ1*01|Mus', 'CTACTGGTACTTCGATGTCTGGGGCGCAGGGACCACGGTCACCGTCTCCTCAG'],
          ['V00770|IGHJ1*02|Mus', 'CTACTGGTACTTCGATGTCTGGGGCGCAGGGACCACGGTCACCGTTTCCTCAG'],
          ['X63164|IGHJ1*03|Mus', 'CTACTGGTACTTCGATGTCTGGGGCACAGGGACCACGGTCACCGTCTCCTCAG'],
          ['V00770|IGHJ2*01|Mus', 'ACTACTTTGACTACTGGGGCCAAGGCACCACTCTCACAGTCTCCTCAG'],
          ['S73821|IGHJ2*02|Mus', 'ACTACTTTGACTACTGGGGCCAAGGCACCTCTCTCACAGTCTCCTCAG']],
         columns=['id', 'sequence']))
])
def test_read_fasta_as_dataframe(infile, expected):
    """Test if a FASTA file can be read as pandas.DataFrame.

    The dataframe contains label name and sequence columns containing the
    corresponding FASTA data (only first five rows).

    Parameters
    ----------
    filename : string
        Location of the FASTA file to be read in.
    expected : pandas.DataFrame
        The expected output pandas dataframe.

    Raises
    -------
    AssertionError
        If the performed test failed.

    """
    result = read_fasta_as_dataframe(infile=infile)
    assert result.head().equals(expected)
