os: linux

language: python
python:
  - "2.7"

install:
  - sudo apt-get install muscle
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements-travis.txt

script:
  - make test

branches:
  only:
    - master
    - /^issue-[0-9]+.*$/
