os: linux

language: python
python:
  - '2.7'

install:
  - sudo apt-get install muscle
  - pip install -U pip
  - pip install .[development]

branches:
  only:
    - master
    - /^issue-[0-9]+.*$/

stages:
  - name: test
    if: branch != master
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - python -m pytest -v tests
    - stage: release
      script:
        - python -m pytest -v tests
      after_success:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - semantic-release publish
