os: osx

osx_image: xcode10

language: python

python:
  - "2.7"

before_install:
  - brew tap brewsci/bio
  - brew outdated muscle || brew upgrade muscle

install:
  - make setup

script:
  - make pytest

branches:
  only:
    - master
