os: linux

language: python
python:
  - '2.7'

install:
  - sudo apt-get install muscle
  - pip install --upgrade pip && pip install --upgrade setuptools
  - make setup

branches:
  only:
    - master
    - /^issue-[0-9]+.*$/

stages:
  - name: test
    if: branch != master
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - make pytest
    - stage: release
      script:
        - make pytest
      after_success:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - semantic-release publish
