##
##	pygor
##		Pygor is part of the IGoR (Inference and Generation of Repertoires) software.
##		Pygor Python package can be used to post process files generated by IGoR.
##		Copyright (C) 2018 Quentin Marcou & Wout van Helvoirt
##

default: help

##	COMMANDS
##

##		make help
##			Display the help information.
##
help:
	@grep "^##.*" ./Makefile

##		make setup
##			Setup the development enviroment from setup.py and installs
##			development requirements in pip.
##
setup:
	python setup.py develop && pip install -r requirements-dev.txt

##		make pytest
##			Run pytest tests from the tests directory on the pygor source.
##
pytest:
	python -m pytest -v tests

##		make clean
##			Removes the old distribution directories and files.
##
clean:
	rm -rf ./dist && rm -rf ./build && find . -name "*.pyc" -type f -delete

##		make build
##			Perfoms clean and builds the new distribution package.
##
build: clean
	python setup.py bdist_wheel

##		make test-deploy
##			Upload all distribution files to PyPI test enviroment.
##
test-deploy:
	python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

##		make deploy
##			Upload all distribution files to PyPI.
##
deploy:
	python -m twine upload dist/*
