# Pygor is part of the IGoR (Inference and Generation of Repertoires) software.
# Pygor Python package can be used to post process files generated by IGoR.
# Copyright (C) 2018 Quentin Marcou & Wout van Helvoirt

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


"""Contains processing functions used in pygor."""


import multiprocessing

import numpy


def multiprocess_array(ary, func, num_workers=1, **kwargs):
    """Applies multiprocessing on a multi array using the given function.

    Parameters
    ----------
    ary : array
        numpy.array or pandas.Dataframe to be split for multiple workers.
    func : Object
        A function object that the workers should apply.
    num_workers : int, optional
        Integer specifying the number of workers (threads) to create. By default
        creates 1 worker.
    **kwargs
        The remaining arguments to be given to the input function.

    Returns
    -------
    list
        Contains the results from each of the workers.

    """
    pool = multiprocessing.Pool(processes=num_workers)
    result = pool.map(func, [(d, kwargs)
                             for d in numpy.array_split(ary, num_workers)])
    pool.close()
    return list(result)
