# Pygor is part of the IGoR (Inference and Generation of Repertoires) software.
# Pygor Python package can be used to post process files generated by IGoR.
# Copyright (C) 2018 Quentin Marcou & Wout van Helvoirt

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


"""SequenceLocator class for locating the CDR3 sequences in the alignment."""


import numpy

from pygor.util.exception import GeneIdentifierException
from pygor.util.processing import multiprocess_array


class SequenceLocator(object):
    """Class for locating CDR3 sequences within the given nucleotide alignment.

    Parameters
    ----------
    alignment : Bio.AlignIO
        An biopython MUSCLE alignement object from alignment.MuscleAligner.
    gene : string
        A gene identifier, either V or J, specifying the alignement's origin.

    Methods
    -------
    get_indices_motifs(custom_motifs=None)
        Returns the indices dictionarys for each of the given motifs in the
        given list.

    """
    def __init__(self, alignment, gene):
        super(SequenceLocator, self).__init__()
        self.alignment = alignment
        self.gene = gene
