# Pygor is part of the IGoR (Inference and Generation of Repertoires) software.
# Pygor Python package can be used to post process files generated by IGoR.
# Copyright (C) 2018 Quentin Marcou & Wout van Helvoirt

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


"""Test file for testing functions/classes in pygor.alignment module."""


from Bio.Align import MultipleSeqAlignment
import pytest

from pygor.alignment.muscle_aligner import MuscleAligner


@pytest.mark.parametrize("fasta_file, expected", [
    ("tests/alignment/data/test.fasta", MultipleSeqAlignment)
])
def test_muscle_aligner(fasta_file, expected):
    """Test if fasta file can be aligned by MUSCLE commandline tool.

    Parameters
    ----------
    fasta_file : string
        A fasts file string location path.
    expected : object
        The expected output type object.

    Raises
    -------
    AssertionError
        If the performed test failed.
    """
    ma = MuscleAligner(fasta_file=fasta_file)
    alignment = ma.get_muscle_alignment()
    assert type(alignment) == expected
